// *** action types contstants *** //
export const GET_MOVIES = 'GET_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const RECEIVE_MOVIE_DETAIL = 'RECEIVE_MOVIE_DETAIL';
export const GET_WATCH_LIST = 'GET_WATCH_LIST';
export const GET_FAVOURITE_LIST = 'GET_FAVOURITE_LIST';
export const RECEIVE_WATCH_LIST = 'RECEIVE_WATCH_LIST';
export const RECEIVE_FAVOURITE_LIST = 'RECEIVE_FAVOURITE_LIST';